# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b01ee74836f19d3d7c167950306a2d70"
application_url = "https://example.com"
embedded = true
name = "sale-report"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"
